CREATE SEQUENCE seq_dim_time START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE seq_dim_location START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE seq_dim_customer START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE seq_dim_product START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE seq_dim_payment_method START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE seq_fact_sales START WITH 1 INCREMENT BY 1;