CREATE SEQUENCE seq_customers START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE seq_addresses START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE seq_accounts START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE seq_tokens START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE seq_brands START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE seq_categories START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE seq_products START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE seq_prices START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE seq_inventories START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE seq_orders START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE seq_order_items START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE seq_deliveries START WITH 1 INCREMENT BY 1;